dns_zone_name = "${DNS_ZONE_NAME}"
region = "${REGION}"
ssl_arn = "${SSL_ARN}"
name = "${ENVIRONMENT_NAME}"
registry_bucket_name = "${REGISTRY_S3_BUCKET_NAME}"
root_volume_size = "${ROOT_VOLUME_SIZE}"
